package src.Chifumi;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        
        Chifumi partie = new Chifumi(3);
        char rejouer = 'O';

        while(rejouer == 'O'){
            partie.raz();
            while(partie.continuer()){
                System.out.println("Tapez 0, 1, ou 2 pour jouer");
                int j1 = scan.nextInt();
                partie.jouer(j1, (int)(Math.random() * 3));
            }
            System.out.println("Souhaitez vous rejouer ? O pour continuer");
            rejouer = scan.next().charAt(0);
        }
            

        scan.close();
    }
}
 